# Generated by Django 4.2 on 2023-04-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_items_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
